### ISSUE TITLE
Quasar Configs

### ISSUE THREAD

**Issue by mecjos** [laraquasar/laraquasar#1]
I want to add sass variables into components. it gives  "@import 'quasar-variables.sass'" error when add lang=scss into style tag.. Could you give detailed info how to use this and where to define quasar.configs in vite.

**Comment by Shun-Ibiki** [comment]
I think you can found configuration on resource/js/app.js
```
        .use(Quasar, {
          plugins : {}, // import Quasar plugins and add here
          iconSet : quasarIconSet,
          config : {
                  //insert config here
            brand : {
                primary: '#F73931',
            },
          }
        })
```

**Comment by mohamad-supangat** [comment]
> I want to add sass variables into components. it gives "@import 'quasar-variables.sass'" error when add lang=scss into style tag.. Could you give detailed info how to use this and where to define quasar.configs in vite.

if you use quasr-variables.sass you can add into vite.config.js you need create in vite.config.js

**Comment by mohamad-supangat** [comment]
@mecjos hay i merge pull request to make working with quasar variables sass

**Comment by mecjos** [comment]
Thank you..

**Comment by mecjos** [comment]
> @mecjos hay i merge pull request to make working with quasar variables sass

Hi Muhammed.. bro I need to add global quasar app.css file into project.. I tried something but I couldn't..

**Comment by mohamad-supangat** [comment]
> > @mecjos hay i merge pull request to make working with quasar variables sass
> 
> Hi Muhammed.. bro I need to add global quasar app.css file into project.. I tried something but I couldn't..

can you share your code here. I don't know what the global app.css that is used means?

**Comment by mecjos** [comment]
> > > @mecjos hay i merge pull request to make working with quasar variables sass
> > 
> > 
> > Hi Muhammed.. bro I need to add global quasar app.css file into project.. I tried something but I couldn't..
> 
> can you share your code here. I don't know what the global app.css that is used means?

Beriefly I want to create my own theme and I add my css codes under "resources/css/app.css" but they doesn't effect app. 

```
export default defineConfig({
    plugins: [
        laravel({
            input: ["resources/css/app.css", "resources/js/app.js"],
            refresh: true,
        }),
        vue({
            template: { transformAssetUrls },
        }),
        svgLoader(),
        quasar({
            autoImportComponentCase: "combined",
            sassVariables: "resources/css/quasar-variables.sass",
        }),
    ],
});
```

here there is written under laravel -> input but doesn't work.. I fixed it by  `@vite(['resources/js/app.js', "resources/css/app.css"])` into app.blade.php header. But how to configure it in config files.. ?

**Comment by mohamad-supangat** [comment]
> > > > @mecjos hay i merge pull request to make working with quasar variables sass
> > > 
> > > 
> > > Hi Muhammed.. bro I need to add global quasar app.css file into project.. I tried something but I couldn't..
> > 
> > 
> > can you share your code here. I don't know what the global app.css that is used means?
> 
> Beriefly I want to create my own theme and I add my css codes under "resources/css/app.css" but they doesn't effect app.
> 
> ```
> export default defineConfig({
>     plugins: [
>         laravel({
>             input: ["resources/css/app.css", "resources/js/app.js"],
>             refresh: true,
>         }),
>         vue({
>             template: { transformAssetUrls },
>         }),
>         svgLoader(),
>         quasar({
>             autoImportComponentCase: "combined",
>             sassVariables: "resources/css/quasar-variables.sass",
>         }),
>     ],
> });
> ```
> 
> here there is written under laravel -> input but doesn't work.. I fixed it by `@vite(['resources/js/app.js', "resources/css/app.css"])` into app.blade.php header. But how to configure it in config files.. ?

wow I see what you are experiencing, you can import app.css into app.js after this line @mecjos 

https://github.com/laraquasar/laraquasar/blob/c9d9439d6c6b60f70f52ca8a6e512e3fdde3e20b/resources/js/app.js#L3


like this
```js
...
import "quasar/src/css/index.sass";
import '../css/app.css';
...
```

**Comment by mecjos** [comment]
@mohamad-supangat ok.. thank you.
