### ISSUE TITLE
SASS error: funtion not found math.div 

### ISSUE THREAD

**Issue by blaigarcia** [laraquasar/laraquasar#11]
**Describe the bug**
SASS error when open the welcome page:
funtion not found math.div  on module node_modules\quasar\src\css\helpers\math.sass

**Solution**
There is an issue on packaje.json  for sass version package:

on line ...       "sass": "1.32.12",
must be ...     "sass": "^1.33.0",

**Comment by mohamad-supangat** [comment]
tanks, great fixing
