### ISSUE TITLE
Quasar Configs

### ISSUE THREAD

**Issue by mecjos** [laraquasar/laraquasar#12]
I couldn't find where to write global app.css file loction in vite config or in app.js  like following prop in quasar config file. 

```
css: [
      'app.scss'
    ],
```

 using same quasar config file in vite config can be possible in future.. for example can we call quasar.config file to place where it should be used..

**Comment by mohamad-supangat** [comment]
check this 

https://github.com/laraquasar/laraquasar/blob/c9d9439d6c6b60f70f52ca8a6e512e3fdde3e20b/vite.config.js#L10
